### ISSUE TITLE
administratives.json to provinces.json

### ISSUE THREAD

**Issue by ljoboy** [devscast/DRC-Base-Data#4]
**Is your feature request related to a problem? Please describe.**
It's confusing to retrieve provinces in administratives.json

**Describe the solution you'd like**
I think that it will be more efficient to rename administratives.json to provinces.json and remove the administratives key inside the json

**Describe alternatives you've considered**
An additional way will be to add that files aside the older one (provinces.json and administratives.json)

**Comment by bernard-ng** [comment]
That a good point, your PR is welcomed

**Comment by bernard-ng** [comment]
@ljoboy any update on this ?

**Comment by ljoboy** [comment]
It's done
